Readme file created
Knawat/dropshipping-woocommerce-wpml-addon pull request #9
Opened 2021-05-17 15:06 UTC by suraj-rathod

2021-05-19 13:30 UTC, iamdharmesh requested changes

2021-05-19 13:30 UTC, iamdharmesh commented on readme.txt
> +Tested up to: 4.8.0
add WP's latest version here.

2021-05-19 13:30 UTC, iamdharmesh commented on readme.txt
> +Tags: dropshipping, woocommerce, woocommerce dropshipping, dropship, woo dropshipping, knawat, knawat dropshipping, multivendor marketplace, WCFM Marketplace, Multi seller, Marketplace, WPML Addon
They show first 5 tags only. So, add WPML in first five 5 tags.

2021-05-19 13:30 UTC, iamdharmesh commented on readme.txt
> +2.
Add screenshots please. in not needed then remove this section please.

2021-05-19 13:30 UTC, iamdharmesh commented on readme.txt
> +WooCommerce DropShipping WPML Addon Translator for WooCommerce Products, Categories, Tags
WooCommerce DropShipping WPML Addon Adds WPML support to Knawat WooCommerce DropShipping plugin, which enable translation of Knawat products, categories and tags using WPML.

This addon is comes with zero configuration you just need to install and activate. rest things will be handled automatically.

2021-05-19 13:32 UTC, suraj-rathod commented on readme.txt
> +WooCommerce DropShipping WPML Addon Translator for WooCommerce Products, Categories, Tags
Thanks for the details @iamdharmesh I will update all points and let you know

2021-05-25 14:43 UTC, suraj-rathod commented on readme.txt
> +Tested up to: 4.8.0
@iamdharmesh please review latest commit i have update it

2021-05-26 05:25 UTC, iamdharmesh approved these changes

2021-05-26 05:27 UTC, merged